# Generated by Django 5.1.5 on 2025-02-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextbookMarketplaceApp', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
